name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14' # Use a valid Node.js version
          registry-url: https://npm.pkg.github.com/
          scope: 'userName' # Correct scope format

      - name: Install Dependencies
        run: npm install

      - name: Publish to npm
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GITHUB_TOKEN }}" > ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
